---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wif-bo-crt
spec:
  secretName: wif-bo-crt-secret
  dnsNames:
  - wif-bo-api.${ENVIRONMENT}.social.gouv.fr
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - wif-bo-api.${ENVIRONMENT}.social.gouv.fr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
