---
kind: Job
apiVersion: batch/v1
metadata:
  name: init-kinto
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - image: ${CI_REGISTRY_IMAGE}/kinto:${IMAGE_TAG}
          name: wif-bo-init-kinto
          env:
            - name: ENVIRONMENT_TYPE
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: ENVIRONMENT_TYPE
            - name: KINTO_BASE_URL
              value: "kinto"
            - name: WIFBO_PG_USER
              value: ${WIFBO_PG_USER}
            - name: WIFBO_PG_PASSWORD
              value: ${WIFBO_PG_PASSWORD}
          resources:
            requests:
              cpu: ${INIT_KINTO_RESOURCE_CPU_REQUEST}
              memory: ${INIT_KINTO_RESOURCE_MEMORY_REQUEST}
            limits:
              cpu: ${INIT_KINTO_RESOURCE_CPU_LIMIT}
              memory: ${INIT_KINTO_RESOURCE_MEMORY_LIMIT}
      restartPolicy: Never
