---
version: "3.8"

services:
  wif-bo-api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
      shm_size: 256M
    env_file: .env
    ports:
      - 4001:4000

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - wif-bo-pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  wif-bo-pgdata:
