#!/bin/bash

if [[ -z "${MAIL_PASSWORD}" ]]; then
  echo "Expect MAIL_PASSWORD to be defined";
  exit 1;
fi

echo -n "${MAIL_PASSWORD}" \
  | parallel --pipe --tee -v {} ::: \
    "sealed_as api-env ${0}"
