apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: api-env
spec:
  encryptedData:
    AGGREGATOR_DATABASE_URL: AgBIXuOh9kfZEUtHYp8XF7RPw3/K9ourtcEJRVldXluWU32JnVymD2NQW31qPOqXqY+2r9EKD2sZAJVsJTvTPi5QZepVypWBhwbF07XN+zbrYupO86ekWzy1V5p0y6SNmlbACvJGkYk8Go+npCn+HnT1ck2g7GnL/YOky/1gD/+ldDa34xEE8RtDoTEr7YWFC/aVnMSqB59YhnqIaJDT3/mM8h0OhFHZSrVgiiK7gbDkdwsYnz3QQBvo9s9bG4HByUZmuZ1JnAq8BKNqccCT6exQe2syW+EGe8HdTUinJCdRrMJMsVdLcvaRdJUd6aPL79OARv8/hH4FwkoSGRM4zA+sGAFl30beFAon4gjXiuRs/1uB6ssCF7hiy6Ap2hK1LCZJYH+f+d4macnnMC5xA/HErUk0iHQHAVHHJJLUa7kiFeAOuw6/Pkr+CrdpKX3c9r2oaCRk6Oy068KkZfvtWteNRxk10fh+QtAaHKKyXIPhumNmewZBtAzPvbE7ZtdR0KIJh4Su4umhBeto0uCWci7WXKKM59DJ9K6V6j7gvG7yBcShRdUX6EAthzbN1m9idOAXI+cQe8acbjPMNZ1sAowqm4qBvCoSzsoENReKOawrGYtPM6dYcMTIIQ4lsjdSkIgYIWoKcHlNhGm4vsmoaUK8SZrb70/ZLxjAmiL7jXTEjT2ZMvkiAeTih8jiXnBEpXl+QXg409ZK6fS/Q5HzpCWaudv0RMGHjnpx4+x5eYUDtC51gpFjxHsHg3/cigzHOh2wAW8t5IJ4qbFEV8XEIjy4V3wPoe9JOBN0t+2J5x/zi4ltRBo7c6Lak/RHmivGKqvvVWllWOIwBwIrOZQf6yj43cEeiZjtWH/JQYn5io9Hrwl+vKo8Yr9/4g==
    API_PREFIX: AgAxPjV5xt1XAbhGtFsXr/D+sMC6mJqeSJq9WPFtfWckYOgWo9Bhj30WbMN8wgqHM3WAcnZqztOUGXwo9R0EpOlDL1qaoHxiHrE8i8eLuTvYRYtCZC+rveLMESO6y3kxSHoAACuU796V2JzcjIIdUwYNACZH3FaJWZWi5qQYZ7hFT0FTj8LjZ9LlMFK4G+L5bkDW2xHRkR+8QhCQzJLT4LCVgCuZ8Ms22c2e5vjlS5kMTqom9XcaCUDFZ3BuTI2HE1ZneoLqk7PRqKtsVxupS31h7ICxTQXOYqJUZ1/t19yHwuTjlVEGbgoXREQZprOQMO6P15Jxnr1WTh9hj/jKAsu4aJG2qrFmQ11BEjySYtBkkky1Xk/O/mC/NtgZ5HQu61f7EVeDpKzGMCtOcqlOOAielKju3XNh/hkj5TSlcOo182BH8nUMwc+vqSI99iV5sZIiCMJ18PKMIl13nQSJZCkxtMSJ9y83yd4LIM7b4pso1luQh5+DYjoAOJ++D/xte0O8tgTNffDibk24U++ZlpSNgxsJR8A3WescJNbAUqtV8S5MvsFeGhNo59QSA8ONfEXCGixzJPoY6rjRiG7if+SZzkVQF1Y5dy20hHBMLbOiF2lcwdDxIESiOX8dpXj7vHmUcRQo61HFEaSNWl3ewvdTL8B6YC2pvX/UMabsXuJsWkAvFN2b0v28TFaCgxB0MgsJUHBzX9h5/INUBDnO4ekj
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: api-env
    type: Opaque

