#!/bin/bash

if [[ -z "${AGGREGATOR_DATABASE_URL}" ]]; then
  echo "Expect AGGREGATOR_DATABASE_URL to be defined";
  exit 1;
fi

echo -n "${AGGREGATOR_DATABASE_URL}" \
  | parallel --pipe --tee -v {} ::: \
    "sealed_as api-env ${0} --scope cluster-wide"
